### PR TITLE
Prise en main du projet à travers modification de la page de connexion

### PR DESCRIPTION
**Pull request by jeromerd75**
## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by jeromerd75** [comment]
> @microsoft-github-policy-service agree [company="{slow tech consulting}"]

**Comment by jeromerd75** [comment]
@microsoft-github-policy-service agree [company="slow tech consulting"]

**Comment by jeromerd75** [comment]
@microsoft-github-policy-service agree

**Comment by jeromerd75** [comment]
@microsoft-github-policy-service agree

**Comment by bobtabor-msft** [comment]
Without any context, I'm afraid I'll need to close this. If you want to provide more background information as to the reason for this PR, please feel free to re-open and discuss. Thank you.

**Pull request closed without merging**
